version: 2
project_name: ip6calc

before:
  hooks:
    - go mod tidy

builds:
  - id: ip6calc
    main: ./cmd/ip6calc
    binary: ip6calc
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/zlobste/ip6calc/internal/cli.Version={{.Version}} -X github.com/zlobste/ip6calc/internal/cli.Commit={{.Commit}} -X github.com/zlobste/ip6calc/internal/cli.BuildDate={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

archives:
  - id: archive
    ids: [ip6calc]
    format_overrides:
      - goos: windows
        formats: [zip]
    # Use conditional to replace darwin with macOS (replacements removed in v2)
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - SECURITY.md
      - CONTRIBUTING.md
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

sboms:
  - id: sbom-archives
    artifacts: archive

signs:
  - artifacts: checksum
    cmd: cosign
    args:
      - sign-blob
      - '--output'
      - '${signature}'
      - '--yes'
      - '${artifact}'
    signature: '${artifact}.sig'
    env:
      - COSIGN_EXPERIMENTAL=1

# NOTE: Homebrew cask and Scoop packaging temporarily disabled because target
# repositories (zlobste/homebrew-tap, zlobste/scoop-bucket) don't exist yet.
# Re-enable by restoring the removed sections below once the repos are created.

release:
  draft: false
  prerelease: auto
  mode: replace

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
